//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_BBSEntities : DbContext
    {
        public DB_BBSEntities()
            : base("name=DB_BBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_ForumInfoStatus> tb_ForumInfoStatus { get; set; }
        public virtual DbSet<tb_ForumReport> tb_ForumReport { get; set; }
        public virtual DbSet<tb_ForumSecond> tb_ForumSecond { get; set; }
        public virtual DbSet<tb_UserByRole> tb_UserByRole { get; set; }
        public virtual DbSet<tb_UserByRoleJoinColumn> tb_UserByRoleJoinColumn { get; set; }
        public virtual DbSet<tb_UsersBySystem> tb_UsersBySystem { get; set; }
        public virtual DbSet<tb_ZY_ForumReportType> tb_ZY_ForumReportType { get; set; }
        public virtual DbSet<tb_ZY_ReportType> tb_ZY_ReportType { get; set; }
        public virtual DbSet<tb_ZY_Sex> tb_ZY_Sex { get; set; }
        public virtual DbSet<tb_Column> tb_Column { get; set; }
        public virtual DbSet<tb_ForumArea> tb_ForumArea { get; set; }
        public virtual DbSet<tb_UsersByCustomer> tb_UsersByCustomer { get; set; }
        public virtual DbSet<tb_ForumClassify> tb_ForumClassify { get; set; }
        public virtual DbSet<tb_ForumMain> tb_ForumMain { get; set; }
    
        public virtual ObjectResult<SP_Get_UsersByCustomer_NotTargetForumArea_Result> SP_Get_UsersByCustomer_NotTargetForumArea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_UsersByCustomer_NotTargetForumArea_Result>("SP_Get_UsersByCustomer_NotTargetForumArea");
        }
    
        public virtual int DBUpdate(string tableName, string setField, string whereField, string andField)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var setFieldParameter = setField != null ?
                new ObjectParameter("SetField", setField) :
                new ObjectParameter("SetField", typeof(string));
    
            var whereFieldParameter = whereField != null ?
                new ObjectParameter("WhereField", whereField) :
                new ObjectParameter("WhereField", typeof(string));
    
            var andFieldParameter = andField != null ?
                new ObjectParameter("AndField", andField) :
                new ObjectParameter("AndField", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DBUpdate", tableNameParameter, setFieldParameter, whereFieldParameter, andFieldParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_Get_UsersByCustomer_NotTargetForumClassify_Result> SP_Get_UsersByCustomer_NotTargetForumClassify()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_UsersByCustomer_NotTargetForumClassify_Result>("SP_Get_UsersByCustomer_NotTargetForumClassify");
        }
    
        public virtual ObjectResult<SP_Get_RoleJoinColumn_Result> SP_Get_RoleJoinColumn(Nullable<int> roleID)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_RoleJoinColumn_Result>("SP_Get_RoleJoinColumn", roleIDParameter);
        }
    }
}
