//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ForumClassify
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ForumClassify()
        {
            this.tb_ForumMain = new HashSet<tb_ForumMain>();
        }
    
        public int ID { get; set; }
        public int ForumAreaID { get; set; }
        public int ForumUserID { get; set; }
        public string ClassifyName { get; set; }
        public string ClassifyLogo { get; set; }
        public string ClassifyInnerLogo { get; set; }
        public int ClassifyOrder { get; set; }
        public Nullable<bool> ClassifyIsleaf { get; set; }
    
        public virtual tb_ForumArea tb_ForumArea { get; set; }
        public virtual tb_UsersByCustomer tb_UsersByCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ForumMain> tb_ForumMain { get; set; }
    }
}
