//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ForumInfoStatus
    {
        public int ID { get; set; }
        public int ForumMainID { get; set; }
        public int ReplyNumber { get; set; }
        public int SeeNumber { get; set; }
        public Nullable<int> LastReplyUserID { get; set; }
        public Nullable<System.DateTime> LastReplytime { get; set; }
    
        public virtual tb_UsersByCustomer tb_UsersByCustomer { get; set; }
        public virtual tb_ForumMain tb_ForumMain { get; set; }
    }
}
